modLoader = "javafml"
loaderVersion = "[36,)"

issueTrackerURL = "https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues"
displayURL = "https://curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition"
logoFile = "logo 160.png"
license = "LGPL-2.1"
credits = "Lewis_McReu for some coding assistance, Vik for the great new art :)"
authors = "Cazsius, Talonos, juliand665"

[[mods]] # no need to indent — we only have one mod anyway

modId = "solcarrot"
version = "${file.jarVersion}"
displayName = "Spice of Life: Carrot Edition"
description = '''
A mod designed to encourage dietary variety!

It does so by rewarding the player for eating a variety of foods instead of punishing them for failing to diversify.
Instead of using the stick, we use the carrot!
'''

# Dependencies are optional.
[[dependencies]]
	modId = "forge"
	mandatory = true
	versionRange = "[36,)"
	ordering = "NONE" # BEFORE or AFTER required if the relationship is not mandatory
	side = "BOTH" # BOTH, CLIENT or SERVER
